version: 1
disable_existing_loggers: True
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  stderr:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - stderr
  uvicorn.access:
    handlers:  # remove handlers for uvicorn access logs
  terra_stac_api.access:
    level: INFO
    handlers:
      - stdout